# Generated by Django 4.0.6 on 2022-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateOfPurchase', models.DateField(auto_now=True)),
                ('sellingPrice', models.PositiveBigIntegerField()),
                ('cars', models.ManyToManyField(related_name='sale_cars', to='car.car')),
                ('customers', models.ManyToManyField(related_name='sale_customers', to='customer.customer')),
            ],
        ),
    ]
