# Generated by Django 4.0.6 on 2022-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('segment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('fuel', models.CharField(choices=[('CNG', 'CNG'), ('DIESEL', 'Diesel'), ('PETROL', 'Petrol')], max_length=6)),
                ('powerSteering', models.IntegerField(choices=[('TRUE', 1), ('FALSE', 0)])),
                ('airBags', models.IntegerField(choices=[('TRUE', 1), ('FALSE', 0)])),
                ('sunRoof', models.IntegerField(choices=[('TRUE', 1), ('FALSE', 0)])),
                ('mattFinish', models.IntegerField(choices=[('TRUE', 1), ('FALSE', 0)])),
                ('musicSystem', models.IntegerField(choices=[('TRUE', 1), ('FALSE', 0)])),
            ],
        ),
    ]
