# Generated by Django 4.0.6 on 2022-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='airBags',
            field=models.BooleanField(choices=[('TRUE', 1), ('FALSE', 0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='mattFinish',
            field=models.BooleanField(choices=[('TRUE', 1), ('FALSE', 0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='musicSystem',
            field=models.BooleanField(choices=[('TRUE', 1), ('FALSE', 0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='powerSteering',
            field=models.BooleanField(choices=[('TRUE', 1), ('FALSE', 0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='sunRoof',
            field=models.BooleanField(choices=[('TRUE', 1), ('FALSE', 0)]),
        ),
    ]
