# Generated by Django 4.0.6 on 2022-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=6)),
                ('income', models.CharField(choices=[('LOW', '0 -$25K'), ('MEDIUM', '$25K-$70K'), ('HIGH', '>$70K')], max_length=8)),
                ('region', models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West')], max_length=8)),
                ('maritalStatus', models.IntegerField(choices=[('MARRIED', 1), ('UNMARRIED', 0)])),
                ('cars', models.ManyToManyField(related_name='cutomer_cars', to='car.car')),
            ],
        ),
    ]
