# Generated by Django 4.0.6 on 2022-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='maritalStatus',
            field=models.CharField(choices=[('MARRIED', 1), ('UNMARRIED', 0)], max_length=9),
        ),
    ]
