# Generated by Django 4.0.6 on 2022-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_airbags_alter_car_mattfinish_and_more'),
        ('customer', '0002_alter_customer_maritalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='cutomer_cars', to='car.car'),
        ),
    ]
